#!/usr/bin/env bash
set -euo pipefail
shopt -s extglob

if [[ "$OSTYPE" != linux* ]]; then
    echo "Skipping Xvfb setup on $OSTYPE."
    return 0
fi

cat <<HEREDOC > /opt/julia
#!/usr/bin/env bash
pkill -9 Xvfb
pkill -9 julia
DISPLAY=:0 xvfb-run -e /dev/stdout -s '-screen 0 1024x768x24' `which julia` "\$@"
HEREDOC

chmod +x /opt/julia

export PATH=/opt:"$PATH"

echo "PATH is now $PATH"
echo "The content of /opt/julia is"
cat /opt/julia
echo "which julia gives `which julia`"
echo "julia -e versioninfo()"
julia -e "using InteractiveUtils; versioninfo()"
