#!/usr/bin/env bash
set -euo pipefail
shopt -s extglob

if [[ "$OSTYPE" != linux* ]]; then
    echo "Skipping Xvfb diagnostics on $OSTYPE."
    return 0
fi

echo "PATH is now $PATH"
echo "The content of /opt/julia is"
cat /opt/julia
echo "which julia gives `which julia`"
